/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import _level from "./level/_level"
import Player from "./game/Player"
import MovingBlock from "./game/MovingBlock"
import ButtonMain from "./UI_object/ButtonMain"
import ButtonSound from "./UI_object/ButtonSound"
import Point from "./game/Point"
import PointType1 from "./game/PointType1"
import PointType2 from "./game/PointType2"
import Move from "./game/Move"
import FallGround from "./game/FallGround"
import ButtonScene from "./UI_object/ButtonScene"
import LastLevel from "./level/LastLevel"
import MenuLevel from "./level/MenuLevel"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=320;
    static height:number=570;
    static scaleMode:string="showall";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MainMenu.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("level/_level.ts",_level);
        reg("game/Player.ts",Player);
        reg("game/MovingBlock.ts",MovingBlock);
        reg("UI_object/ButtonMain.ts",ButtonMain);
        reg("UI_object/ButtonSound.ts",ButtonSound);
        reg("game/Point.ts",Point);
        reg("game/PointType1.ts",PointType1);
        reg("game/PointType2.ts",PointType2);
        reg("game/Move.ts",Move);
        reg("game/FallGround.ts",FallGround);
        reg("UI_object/ButtonScene.ts",ButtonScene);
        reg("level/LastLevel.ts",LastLevel);
        reg("level/MenuLevel.ts",MenuLevel);
    }
}
GameConfig.init();